name: Get Next Version

on:
  workflow_call:
    inputs:
      major:
        description: "Update major version"
        required: false
        type: boolean
        default: false
      minor:
        description: "Update minor version"
        required: false
        type: boolean
        default: false
      patch:
        description: "Update patch version"
        required: false
        type: boolean
        default: false
    outputs:
      output:
        description: "Next version"
        value: ${{ jobs.get-next-version.outputs.output }}
      test:
        description: "Test"
        value: "test"

jobs:
  get-next-version:
    name: Get Next Version
    runs-on: ubuntu-latest
    env:
      CURRENT_VERSION: ""
    outputs:
      output: ${{ steps.next-version.outputs.output }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Currnet Version
        run: |
          echo "CURRENT_VERSION=$(grep '^version =' Cargo.toml | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: Get Next version
        id: next-version
        shell: bash
        run: |
          VERSION_TYPE=""
          if [ "${{ inputs.major }}" == "true" ]; then
            VERSION_TYPE="major"
          elif [ "${{ inputs.minor }}" == "true" ]; then
            VERSION_TYPE="minor"
          elif [ "${{ inputs.patch }}" == "true" ]; then
            VERSION_TYPE="patch"
          fi
          echo CURRENT_VERSION=$CURRENT_VERSION
          NEXT_VERSION=`bash .github/workflows/get_next_version.sh $VERSION_TYPE`

          echo "NEXT_VERSION=$NEXT_VERSION"
          echo "output=$NEXT_VERSION" >> $GITHUB_OUTPUT
