name: Build, Release and Create draft notes

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types:
      - closed

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Build Release Binary
        run: cargo build --release

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{steps.previous_tag.outputs.tag}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.previous_tag.outputs.tag}}
          files: |
            target/release/tagcm
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
