name: Build, Release and Create draft notes

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Build Release Binary
        run: cargo build --release

      - name: "Get Current tag"
        id: current_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0

      - name: "Check tag version"
        if: ${{ steps.current_tag.outputs.tag != github.ref_name }}
        run: echo ${{ steps.current_tag.outputs.tag }} and ${{ github.ref_name }} are not the same && exit 1

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{steps.current_tag.outputs.tag}}
          append_body: true
          draft: false
          publish: true
          latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
