name: Build, Release and Create draft notes

on:
  push:
    branches:
      - release

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Build Release Binary
        run: cargo build --release

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/tagcm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
