name: Build, Release and Create draft notes

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          depth: 0

      - name: Check if main branch
        if: ${{ endsWith(github.ref_name, 'main') }} == false
        run: echo ${{ github.ref_name}} is not main branch && exit 1

      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Build Release Binary
        run: cargo build --release

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0
      
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}

      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{steps.semvers.outputs.patch}}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

