name: update draft notes

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update_draft_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: fetch tag
        run: git fetch --tags origin

      - name: print pwd and tag
        run: pwd && git tag
    
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Build Release Binary
        run: cargo build --release

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}

      - name: Draft Release Notes
        id: draft_release_notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{steps.semvers.outputs.minor}}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.draft_release_notes.outputs.tag_name}}
          draft: true
          append_body: true
          files: |
            target/release/tagcm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}