name: update draft notes

on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  contents: write

jobs:
  update_draft_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      
      - name: Build Release Binary
        run: cargo build --release

      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previous_tag.outputs.tag }}

      - name: Draft Release Notes
        id: draft_release_notes
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{steps.semvers.outputs.minor}}
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.semvers.outputs.patch}}
          files: |
            target/release/tagcm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}